services:
  bot:
    build: .
    environment:
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DATABASE_URL: "postgres://modmail:${POSTGRES_PASSWORD}@db/modmail"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "modmail"
    volumes:
      - modmail-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  modmail-data:
