services:
  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:16
    env_file: .env.db
    environment:
      POSTGRES_USER: modmail
    volumes:
      - ./persisted/db/data:/var/lib/postgresql/data
    restart: unless-stopped
